version: "3.9"
services:
  db:
    container_name: db-trabajo666
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: trabajo666_db
      MYSQL_USER: trabajo666
      MYSQL_PASSWORD: 123456
    networks:
      - net-trabajo666
  web:
    container_name: trabajo666-web
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-trabajo666
networks:
  net-trabajo666:
    
